### ISSUE TITLE
Not able to compile and run sample

### ISSUE THREAD

**Issue by Vishwa-mobmaxime** [styrken/xamarin-ios-zendesk-binding#1]
![screen shot 2019-01-17 at 3 49 13 pm](https://user-images.githubusercontent.com/46779911/51311684-79488a80-1a6f-11e9-8231-ef27460273a9.png)

Here is the snap of errors.

**Comment by styrken** [comment]
Hey @Vishwa-mobmaxime . Thanks for reaching out.

Did you figure out what was wrong? I have not seen this kind of error before. Do you have sample project that I can test it in ?

**Comment by Vishwa-mobmaxime** [comment]
Hey,
Thanks for your reply. That was issue with visual studio or xcode version.
After updating them to latest version it worked fine.
I have one more question, Do you have any plan for creating zendesk chat
sdk binding for xamarin?
--
Thanks,
Vishwa Patel

**Comment by styrken** [comment]
Ok, that sounds great :-) Happy it worked out.

At the moment we do not have any plans for a Zendesk Chat binding.
